version: '3.9'
services:
  budgetting-api:
    image: app:latest
    build:
      context: .
    environment:
      PLAID_CLIENT_ID: /run/secrets/plaid_client_id
      PLAID_SECRET: /run/secrets/plaid_secret
      GOOGLE_CLIENT_ID: /run/secrets/google_client_id
    secrets:
      - plaid_client_id
      - plaid_secret
    ports:
      - "8080:8080"

secrets:
  plaid_client_id:
    file: ./credentials/plaid_client_id.txt
  plaid_secret:
      file: ./credentials/plaid_secret.txt
  google_client_id:
      file: ./credentials/google_client_id.txt