#version: '3.9'
#services:
#  budgetting-api:
#    image: budgetting-api:${IMAGE_TAG}
#    build:
#      context: .
#    environment:
#      PLAID_CLIENT_ID: /run/secrets/plaid_client_id
#      PLAID_SECRET: /run/secrets/plaid_secret
#      GOOGLE_CLIENT_ID: /run/secrets/google_client_id
#    secrets:
#      - plaid_client_id
#      - plaid_secret
#      - google_client_id
#    ports:
#      - "8080:8080"
#    network_mode: "bridge"
#
#secrets:
#  plaid_client_id:
#    file: ../credentials/plaid_client_id.txt
#  plaid_secret:
#      file: ../credentials/plaid_secret.txt
#  google_client_id:
#      file: ../credentials/google_client_id.txt
#
