spring:
  application:
    name: api

plaid:
    clientId: ${PLAID_CLIENT_ID:/run/secrets/plaid_client_id}
    secret: ${PLAID_SECRET:/run/secrets/plaid_secret}

google:
  clientId: ${GOOGLE_CLIENT_ID:/run/secrets/google_client_id}